version: 2.1

jobs:
  # say-hello
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # setup environment and install dependencies
  setup-environment:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies (via Makefile)
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
        
  # test lints
  test-lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: make lint
          command: |
            . venv/bin/activate
            make lint

  # build docker image
  build-docker:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: build docker
          command: |
            ./run_docker.sh
  
  # upload docker to Dockerhub
  upload-docker:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: upload docker
          command: |
            ./upload_docker.sh
    



workflows:
  capstone-workflow:
    jobs:
      - say-hello
      - setup-environment
      - test-lint
      - build-docker
      - upload-docker












